# Generated by Django 3.1.3 on 2020-11-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('phone', models.CharField(max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('payment_method', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
