# Generated by Django 3.1.3 on 2020-11-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201112_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment_method',
        ),
    ]
