# Generated by Django 3.1.3 on 2020-11-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201125_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='session_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
