# Generated by Django 3.1.3 on 2020-11-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reservation_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='session_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
