# Generated by Django 3.1.3 on 2020-11-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201127_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='party_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='secondary_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='secondary_phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
