# Generated by Django 3.1.3 on 2020-11-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201128_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
    ]
