# Generated by Django 3.1.3 on 2020-11-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201102_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
