# Generated by Django 3.1.3 on 2020-11-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201105_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(default='', max_length=15),
        ),
    ]
